name: 'Artifacts upload'
description: 'upload yours files to Artifacts server'
inputs:
  sources:
    description: 'One or more directories / files to upload '
    required: true
    default: '.'
  artifacts-url:
    description: 'Url to the Artifacts web server'
    required: true
  username:
    description: 'Artifacts username'
    required: false
  password:
    description: 'Artifacts password'
    required: false
outputs:
  artifacts-link:
    description: ''
    value: ${{ steps.set-artifacts-link.outputs.artifacts-link }}
  artifacts-name:
    description: ''
    value: ${{ steps.artifacts-name.outputs.artifacts-name }}
runs:
  using: "composite"
  steps:
    # TODO uses key is not currently supported in composite action, so this part is copy / past
    - name: Setup new properties for artifacts name
      id: properties
      run: |
        echo "::set-output name=repository::$(echo ${{ github.repository }} | sed 's/\//:/')"
        echo "::set-output name=commit-timestamp::$(date --date='${{ github.event.head_commit.timestamp }}' +"%s")"
        echo "::set-output name=commit-short-revision::$(echo -n '${{ github.sha }}' | cut -c1-10)"
        echo "::set-output name=workflow-name::$(echo -n '${{ github.workflow }}' | sed 's/\W/-/g' | sed 's/^-//g')"
      shell: bash
    - name: Setup artifacts name property
      id: artifacts-name
      run: "echo ::set-output name=artifacts-name::\
        github:\
        ${{ steps.properties.outputs.repository }}:\
        staging-\
        ${{ steps.properties.outputs.commit-timestamp }}.\
        ${{ steps.properties.outputs.commit-short-revision }}.\
        ${{ steps.properties.outputs.workflow-name }}.\
        ${{ github.run_number }}"
      shell: bash
    - id: additional-xargs-args
      shell: bash
      run : |
        if [ $(cat /etc/*-release | grep alpine | wc -l) -eq 0 ]; then
                echo "::set-output name=args::'-P 16'"
        fi
    - name: push artifacts to server
      shell: bash
      run: |
        find -L ${{ inputs.sources }} -type f -print0 | \
          sed -e "s:\\(^\\|\\x0\\)\\./:\\1:g" | \
          xargs -0 -n 1 -t ${{ steps.additional-xargs-args.outputs.args }} -I @ sh -c \
          'curl -u ${{ inputs.username }}:${{ inputs.password }} --silent --fail --show-error --max-time 3600 -T "@" \
          "${{ inputs.artifacts-url }}/upload/${{ steps.artifacts-name.outputs.artifacts-name }}/"$(echo "@" | sed -e "s: :%20:g")'
