on: [push]
name: test action

jobs:
  push-artifacts-action:
    runs-on: ubuntu-latest
    name: A job that push file on artifacts
    steps:
      - uses: actions/checkout@v1
      - id: set-artifacts-url
        run: echo "::set-output name=url::${{ secrets.ARTIFACTS_URL }}"
      - id: artifacts-upload
        uses: ./
        with:
          artifacts-url: ${{ secrets.ARTIFACTS_URL }}
          username: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          sources: action.yml README.md
      - name: Download file
        run: curl -u  ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}  --silent --fail --show-error  --max-time 3600 ${{ steps.artifacts-upload.outputs.artifacts-link }}/README.md > upload_README.md
      - name: Compare files
        run: cmp --silent upload_README.md ./README.md
      - name: Download file with artifacts-link
        run: curl -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}  --silent --fail --show-error --max-time 3600 ${{ steps.artifacts-upload.outputs.artifacts-link }}/action.yml > upload_action.yml
      - name: Download with  artifacts-url and artifacts-name
        run: curl -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}  --silent --fail --show-error --max-time 3600 ${{ steps.set-artifacts-url.outputs.url }}/builds/${{ steps.artifacts-upload.outputs.artifacts-name }}/action.yml > name_action.yml
      - name: Compare files
        run: cmp --silent upload_action.yml ./name_action.yml
      - name: Compate files2
        run: cmp --silent upload_action.yml ./action.yml

  test_upload_lot_of_files:
    runs-on: ubuntu-latest
    name: A job that push a lot of files on artifacts
    steps:
      - uses: actions/checkout@v1
      - name: create one handrund file
        run: mkdir -p test-files && for i in {1..100}; do echo $RANDOM > ./test-files/$RANDOM.txt; done
      - name: Push handrund files
        uses: ./
        with:
          artifacts-url: ${{ secrets.ARTIFACTS_URL }}
          username: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          sources: ./test-files

  test_upload_a_big_file:
    runs-on: ubuntu-latest
    name: A job that push a big file on artifacts
    steps:
      - uses: actions/checkout@v1
      - name: create one big file
        run:  truncate -s 40K big_file.img # TODO This is the biggest size i could push, Editing ingress config to allow bigger file should patch the problem
      - name: Push on big file
        id: artifacts-upload
        uses: ./
        with:
          artifacts-url: https://artifacts-devl.scality.net
          username: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          sources: ./big_file.img
      - id: artifacts-setup
        uses: scality/action-artifacts-setup@0.0.0
      - name: virify naming betwin upload and setup action
        if: ${{ steps.artifacts-upload.outputs.artifacts-name }} != ${{ steps.artifacts-setup.outputs.artifacts-name }}
        run: exit 1
      - name: Download file
        run: curl -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }} --silent --fail --show-error --max-time 3600 ${{ steps.artifacts-upload.outputs.artifacts-link }}/big_file.img > upload_big_file.img
      - name: Compare files
        run: cmp --silent upload_big_file.img ./big_file.img
