on: [push]
name: Test action

jobs:
  push_artifacts_action:
    runs-on: ubuntu-latest
    name: A job that push file on artifacts
    steps:
      - uses: actions/checkout@v1
      - id: Test-action
        uses: ./
        with:
          artifacts_url: https://artifacts-devl.scality.net
          username: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          sources: action.yml README.md
