on: [push]
name: Test action

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - id: foo
        uses: scality/action-artifacts-upload@v0.2.0
        with:
          artifacts_url: https://artifacts-devl.scality.net
          username: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          sources: action.yml README.md
